apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: public.ecr.aws/l8y8o6k1/my-django-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: pollsdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: DB_HOST
          value: postgres  
        - name: DB_PORT
          value: "5432"
